{{- if ((.Values.server.secrets).create) }}
{{- $key := trimSuffix "/" .Values.server.secrets.path }}
{{- if not (hasSuffix $key ".secrets.enc.yaml") }}
{{- $key = printf "%s/.secrets.enc.yaml" $key }}
{{- end }}
apiVersion: victor.kyber.network/v1alpha1
kind: VictorSecret
metadata:
  name: {{ include "base-service.fullname" . }}
spec:
  secretPath: {{ $key }}
  {{- if .Values.server.secrets.target }}
  target:
    {{- toYaml .Values.server.secrets.target | nindent 4 }}
  {{- end }}
{{- end }}
